[versions]
nyx = "0.2.3"

axion-release = "1.18.16"

minotaur = "2.8.7"

loom = "1.9.2"
minecraft = "1.21.4"
fabric-loader = "0.16.9"
fabric-yarn = "1.21.4+build.2"

mixin = "0.15.4+mixin.0.8.7"
mixinextras = "0.4.1"

[plugins]
nyx = { id = "ca.solo-studios.nyx", version.ref = "nyx" }

axion-release = { id = "pl.allegro.tech.build.axion-release", version.ref = "axion-release" }

fabric-loom = { id = "fabric-loom", version.ref = "loom" }

minotaur = { id = "com.modrinth.minotaur", version.ref = "minotaur" }

[libraries]

minecraft = { group = "com.mojang", name = "minecraft", version.ref = "minecraft" }

yarn-mappings = { group = "net.fabricmc", name = "yarn", version.ref = "fabric-yarn" }

fabric-loader = { group = "net.fabricmc", name = "fabric-loader", version.ref = "fabric-loader" }

sponge-mixin = { group = "net.fabricmc", name = "sponge-mixin", version.ref = "mixin" }
mixinextras = { group = "io.github.llamalad7", name = "mixinextras-fabric", version.ref = "mixinextras" }
